export XMODIFIERS="@im=ibus"
export XIM=ibus
export XIM_PROGRAM=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export LC_CTYPE=zh_CN.UTF-8
export LANG=zh_CN.UTF-8

ibus-daemon -dr --xim
xset r rate 300
(sleep 30 && nohup /opt/nutstore/bin/nutstore-pydaemon.py >/dev/null 2>&1) &
exec dbus-launch awesome
